changelog:
  exclude:
    labels:
      - internal
      - release
    authors:
      - github-actions[bot]
  categories:
    - title: Breaking changes
      labels:
        - breaking
    - title: New and improved
      labels:
        - enhancement
    - title: Fixes
      labels:
        - bug
    - title: Documentation
      labels:
        - documentation
    - title: Other changes
      labels:
        - "*"
