// Generated by scripts/generate-interface.mjs. Do not edit.

import type { DetailedHTMLProps, HTMLAttributes } from 'react'
import type { SdsTabsChangeDetail, SdsToastCloseReason, SdsToggleDetail } from '@cmu-sei/sds-lite'
import type { SdsDropdownElement } from '@cmu-sei/sds-lite/dropdown'
import type { SdsPopoverElement } from '@cmu-sei/sds-lite/popover'
import type { SdsTabsElement } from '@cmu-sei/sds-lite/tabs'
import type { SdsTooltipElement } from '@cmu-sei/sds-lite/tooltip'
import type { SdsToastElement } from '@cmu-sei/sds-lite/toast'

export type SdsElementProps<Element extends HTMLElement> =
  DetailedHTMLProps<HTMLAttributes<Element>, Element>

export type SdsDropdownProps = SdsElementProps<SdsDropdownElement> & {
  "open"?: boolean
  "placement"?: "block-start" | "block-start-start" | "block-start-end" | "block-end" | "block-end-start" | "block-end-end" | "inline-start" | "inline-start-start" | "inline-start-end" | "inline-end" | "inline-end-start" | "inline-end-end"
  "offset"?: number
  "width"?: "auto" | "sm" | "md" | "lg" | "xl" | "2xl"
  "hide-caret"?: boolean
  "onsds-toggle"?: (event: CustomEvent<SdsToggleDetail>) => void
}

export type SdsPopoverProps = SdsElementProps<SdsPopoverElement> & {
  "open"?: boolean
  "placement"?: "block-start" | "block-start-start" | "block-start-end" | "block-end" | "block-end-start" | "block-end-end" | "inline-start" | "inline-start-start" | "inline-start-end" | "inline-end" | "inline-end-start" | "inline-end-end"
  "offset"?: number
  "width"?: "auto" | "sm" | "md" | "lg" | "xl" | "2xl"
  "onsds-toggle"?: (event: CustomEvent<SdsToggleDetail>) => void
}

export type SdsTabsProps = SdsElementProps<SdsTabsElement> & {
  "value"?: string
  "activation"?: "automatic" | "manual"
  "orientation"?: "horizontal" | "vertical"
  "size"?: "md" | "lg"
  "tone"?: "neutral" | "accent" | "info" | "success" | "warning" | "danger"
  "variant"?: "folder" | "block" | "underline"
  "onsds-change"?: (event: CustomEvent<SdsTabsChangeDetail>) => void
}

export type SdsTooltipProps = SdsElementProps<SdsTooltipElement> & {
  "placement"?: "block-start" | "block-start-start" | "block-start-end" | "block-end" | "block-end-start" | "block-end-end" | "inline-start" | "inline-start-start" | "inline-start-end" | "inline-end" | "inline-end-start" | "inline-end-end"
  "offset"?: number
}

export type SdsToastProps = SdsElementProps<SdsToastElement> & {
  "open"?: boolean
  "tone"?: "neutral" | "accent" | "info" | "success" | "warning" | "danger"
  "duration"?: number
  "persistent"?: boolean
  "onsds-open"?: (event: CustomEvent<void>) => void
  "onsds-close"?: (event: CustomEvent<{ reason: SdsToastCloseReason }>) => void
}

declare module 'react' {
  namespace JSX {
    interface IntrinsicElements {
      "sds-dropdown": SdsDropdownProps
      "sds-popover": SdsPopoverProps
      "sds-tabs": SdsTabsProps
      "sds-tooltip": SdsTooltipProps
      "sds-toast": SdsToastProps
    }
  }
}

declare global {
  namespace JSX {
    interface IntrinsicElements {
      "sds-dropdown": SdsDropdownProps
      "sds-popover": SdsPopoverProps
      "sds-tabs": SdsTabsProps
      "sds-tooltip": SdsTooltipProps
      "sds-toast": SdsToastProps
    }
  }
}
