// Generated by scripts/generate-interface.mjs. Do not edit.

import type { DefineComponent } from 'vue'
import type { SdsTabsChangeDetail, SdsToastCloseReason, SdsToggleDetail } from '@cmu-sei/sds-lite'

export interface SdsComboboxProps {
  "filter"?: "automatic" | "manual"
  "keep-open"?: boolean
  onSdsSelect?: (event: CustomEvent<{ option: HTMLLIElement }>) => void
}

export interface SdsDropdownProps {
  "open"?: boolean
  "placement"?: "block-start" | "block-start-start" | "block-start-end" | "block-end" | "block-end-start" | "block-end-end" | "inline-start" | "inline-start-start" | "inline-start-end" | "inline-end" | "inline-end-start" | "inline-end-end"
  "offset"?: number
  "width"?: "auto" | "sm" | "md" | "lg" | "xl" | "2xl"
  "hide-caret"?: boolean
  onSdsToggle?: (event: CustomEvent<SdsToggleDetail>) => void
}

export interface SdsPopoverProps {
  "open"?: boolean
  "placement"?: "block-start" | "block-start-start" | "block-start-end" | "block-end" | "block-end-start" | "block-end-end" | "inline-start" | "inline-start-start" | "inline-start-end" | "inline-end" | "inline-end-start" | "inline-end-end"
  "offset"?: number
  "width"?: "auto" | "sm" | "md" | "lg" | "xl" | "2xl"
  onSdsToggle?: (event: CustomEvent<SdsToggleDetail>) => void
}

export interface SdsTabsProps {
  "value"?: string
  "activation"?: "automatic" | "manual"
  "orientation"?: "horizontal" | "vertical"
  "size"?: "md" | "lg"
  "tone"?: "neutral" | "accent" | "info" | "success" | "warning" | "danger"
  "variant"?: "folder" | "block" | "underline"
  onSdsChange?: (event: CustomEvent<SdsTabsChangeDetail>) => void
}

export interface SdsTooltipProps {
  "placement"?: "block-start" | "block-start-start" | "block-start-end" | "block-end" | "block-end-start" | "block-end-end" | "inline-start" | "inline-start-start" | "inline-start-end" | "inline-end" | "inline-end-start" | "inline-end-end"
  "offset"?: number
}

export interface SdsToastProps {
  "open"?: boolean
  "tone"?: "neutral" | "accent" | "info" | "success" | "warning" | "danger"
  "duration"?: number
  "persistent"?: boolean
  onSdsOpen?: (event: CustomEvent<void>) => void
  onSdsClose?: (event: CustomEvent<{ reason: SdsToastCloseReason }>) => void
}

declare module 'vue' {
  export interface GlobalComponents {
    "sds-combobox": DefineComponent<SdsComboboxProps>
    "sds-dropdown": DefineComponent<SdsDropdownProps>
    "sds-popover": DefineComponent<SdsPopoverProps>
    "sds-tabs": DefineComponent<SdsTabsProps>
    "sds-tooltip": DefineComponent<SdsTooltipProps>
    "sds-toast": DefineComponent<SdsToastProps>
  }
}

export {}
